SOCIAL_AUTH_TWITTER_KEY = '8KXqqvgCD7CJr3oPNTRgfMEhA'
SOCIAL_AUTH_TWITTER_SECRET = 'rwQJV94MQeQ8MZBMIZzWPKoNPRfGElltkmzsJKduKjqzZqPZlj'

SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/home/'
SOCIAL_AUTH_LOGIN_URL = '/'